Repository SnowflurrySDK/Snowflurry.jl, pull requests merged in 2023-04, with the labels that each got.

#122 Feat/add swap gate
  docs/src/library.md
  src/Snowflake.jl
  src/core/quantum_circuit.jl
  src/core/quantum_gate.jl
  test/circuit.jl
  test/gate.jl
Labels: gate

#130 Feat/add half-Pauli gates
  docs/src/library.md
  src/Snowflake.jl
  src/core/quantum_circuit.jl
  src/core/quantum_gate.jl
  test/gate.jl
Labels: gate

#134 Feat/cast swap, iswap, and cx to cz transpilers
  docs/src/library.md
  src/Snowflake.jl
  src/anyon/anyon.jl
  src/core/quantum_circuit.jl
  src/core/transpile.jl
  test/circuit.jl
  test/transpile.jl
Labels: transpiler

#138 Feat/decompose toffoli
  src/Snowflake.jl
  src/anyon/anyon.jl
  src/core/transpile.jl
  test/transpile.jl
Labels: transpiler

#140 Fix/131
  src/core/quantum_circuit.jl
  test/circuit.jl
Labels: bug

#133 Feat/place qubits onto a line
  .github/workflows/test_documentation.yml
  docs/make.jl
  src/Snowflake.jl
  src/anyon/anyon.jl
  src/core/quantum_gate.jl
  src/core/transpile.jl
  test/gate.jl
  test/transpile.jl
Labels: transpiler

#155 Docs/add single qubit readout fidelity example
  docs/src/examples/index.md
  docs/src/examples/introductory.md
  docs/src/examples/introductory/single_qubit_readout_fidelity.md
  docs/src/images/empty_circuit.svg
  docs/src/images/readout_zero_bloch.svg
  docs/src/images/single_qubit_readout_circuit.svg
Labels: documentation

#158 Docs/get qpu metadata example
  docs/src/examples/introductory.md
  docs/src/examples/introductory/get_qpu_metadata.md
  docs/src/examples/introductory/single_qubit_readout_fidelity.md
  examples/get_qpu_metadata.jl
  examples/single_qubit_readout_fidelity.jl
Labels: documentation

#152 Docs/update readme
  .github/workflows/CI.yml
  .github/workflows/deploy_documentation.yml
  .github/workflows/test_documentation.yml
  README.md
  codecov.yml
  docs/make.jl
  docs/src/contributing.md
  docs/src/getting_started.md
  docs/src/images/cnot_circuit.svg
  docs/src/index.md
  examples/bellstate_hardware.jl
  examples/rabi_flip_sim.jl
  examples/simulate_bell_state.jl
  src/anyon/anyon.jl
  src/anyon/qpu_interface.jl
  test/mock_functions.jl
  test/qpu_interface.jl
Labels: documentation

#159 Docs/excitation demonstration
  docs/src/examples/introductory.md
  docs/src/examples/introductory/excitation_demonstration.md
  docs/src/images/excitation_bloch.svg
  docs/src/images/excitation_circuit.svg
  docs/src/images/x_ket_equations.svg
  docs/src/images/x_matrix.svg
  docs/src/images/x_matrix_equations.svg
  examples/excitation_demonstration.jl
Labels: documentation

#160 Docs/hadamard transpilation
  docs/src/examples/introductory.md
  docs/src/examples/introductory/hadamard_transpilation.md
  docs/src/images/hadamard_bloch.svg
  docs/src/images/hadamard_circuit.svg
  docs/src/images/hadamard_matrix.svg
  docs/src/images/transpiled_hadamard_circuit.svg
  examples/hadamard_transpilation.jl
Labels: documentation

#186 Docs/clean up coverage and move contributing page
  coverage.jl
  docs/src/contributing.md
  docs/src/development.md
  docs/src/index.md
Labels: documentation

#183 Docs/asynchronous jobs
  README.md
  docs/src/examples/advanced/asynchronous_jobs.md
  docs/src/examples/index.md
  docs/src/examples/introductory.md
  docs/src/examples/introductory/entanglement_demonstration.md
  docs/src/examples/introductory/excitation_demonstration.md
  docs/src/examples/introductory/hadamard_transpilation.md
  docs/src/examples/introductory/single_qubit_readout_fidelity.md
  docs/src/getting_started.md
  docs/src/images/bell_circuit.svg
  docs/src/images/cnot_circuit.svg
  examples/asynchronous_jobs.jl
  examples/entanglement_demonstration.jl
  examples/excitation_demonstration.jl
  examples/hadamard_transpilation.jl
  examples/single_qubit_readout_fidelity.jl
  src/anyon/qpu_interface.jl
  test/mock_functions.jl
  test/qpu_interface.jl
Labels: documentation

#185 Docs/small fixes
  docs/make.jl
  docs/src/assets/visualize/plot_bloch_sphere_animation_for_ket.html
  docs/src/assets/visualize/plot_bloch_sphere_animation_for_operator.html
  docs/src/assets/visualize/plot_bloch_sphere_animation_without_interpolation.html
  docs/src/assets/visualize/plot_bloch_sphere_for_circuit.png
  docs/src/assets/visualize/plot_bloch_sphere_for_ket.png
  docs/src/assets/visualize/plot_bloch_sphere_for_operator.png
  docs/src/assets/visualize/plot_green_bloch_sphere.png
  docs/src/assets/visualize/plot_histogram.png
  docs/src/assets/visualize/viz_wigner.png
  docs/src/examples/index.md
  docs/src/qc/basics.md
  docs/src/qc/overview.md
  docs/src/simulating_quantum_systems.md
  docs/src/tutorials/advanced/asynchronous_jobs.md
  docs/src/tutorials/index.md
  docs/src/tutorials/introductory/entanglement_demonstration.md
  docs/src/tutorials/introductory/excitation_demonstration.md
  docs/src/tutorials/introductory/get_qpu_metadata.md
  docs/src/tutorials/introductory/hadamard_transpilation.md
  docs/src/tutorials/introductory/single_qubit_readout_fidelity.md
  tutorials/asynchronous_jobs.jl
  tutorials/entanglement_demonstration.jl
  tutorials/excitation_demonstration.jl
  tutorials/get_qpu_metadata.jl
  tutorials/hadamard_transpilation.jl
  tutorials/simulate_bell_state.jl
  tutorials/single_qubit_readout_fidelity.jl
Labels: documentation
